# Generated by Django 5.0 on 2023-12-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
    ]
